<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Auth.Domain\Auth.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\Auth\Commands\Logout\" />
    <Folder Include="Features\Auth\Queries\" />
    <Folder Include="Features\Users\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.2.0" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="MediatR" Version="14.2.0" />
  </ItemGroup>

</Project>
